import Head from "next/head";
import Navbar from "../components/Navbar";
import About from "../components/About";
import Projects from "../components/Projects";
import Contact from "../components/Contact";

import productDetailsData from "../data/project-details.json";

export async function getStaticProps(context) {
  return {
    props: {
      productDetails: productDetailsData,
    },
  };
}

const Home = (props) => {
  return (
    <div className="m-auto">
      <Head>
        <title>Mitchell Gruner Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navbar />

      <div className="2xl:max-w-screen-2xl m-auto">
        <About />
        <Projects productDetails={props} />
  
        {/* <div id="projectsInfo" className="h-auto mt-2 mb-16 xs:mb-20 sm:mb-24 md:mb-32 md:mt-2 lg:mb-36 xl:mb-40 2xl:mb-44">
          {props.productDetails.map((productDetails) => {
            return (
              <ProjectsInfo
                key={productDetails.id}
                image={productDetails.image}
                name={productDetails.name}
                description={productDetails.description}
                demo={productDetails.demo}
                code={productDetails.code}
                video={productDetails.video} 
              />
            );
          })}
        </div> */}

        <Contact />
      </div>
    </div>
  )
}

export default Home;