import Head from "next/head";
import Navbar from "@/components/Navbar";
import About from "@/components/About";
import Projects from "@/components/Projects";
import Contact from "@/components/Contact";

export default function Home() {
  return (
    <div className="2xl:max-w-screen-2xl m-auto" onScroll={this.listenScrollEvent.bind(this)}>
      <Head>
        <title>Mitchell Gruner Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navbar />
      <About />
      <Projects />
      <Contact />
    </div>
  )
}
