import Head from "next/head";
import Navbar from "@/components/Navbar";

export default function Home() {
  return (
    <div className="2xl:max-w-screen-2xl m-auto">
      <Head>
        <title>Mitchell Gruner Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navbar />
    </div>
  )
}
